name: Flask CI/CD
on:
  push:
    branches: [ main ]

jobs:
  # 阶段1：验证 & 测试
  test:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 配置Python3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: 代码环境校验
        run: |
          python -V
          pip install flask
          python -c "import flask;print('Python测试通过')"

  # 阶段2：构建Docker镜像，依赖test完成后执行
  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: 拉取项目代码
        uses: actions/checkout@v4

      - name: 构建flask-web镜像
        run: docker build -t flask-web .

  # 阶段3：远程SSH部署至阿里云ECS
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: 拉取代码
        uses: actions/checkout@v4

      - name: 加载SSH私钥
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH远程更新代码+重建容器
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} << 'EOF'
          cd /home/gxy20/simple-web-cicd
          git pull origin main
          docker stop flask-web || true
          docker rm flask-web || true
          docker build -t flask-web .
          docker run -d --name flask-web -p 80:5000 flask-web
          echo "容器部署启动完成"
EOF

  # 阶段4：流水线执行结果通知
  notify:
    runs-on: ubuntu-latest
    needs: deploy
    if: always
    steps:
      - name: 流水线完成通知
        run: echo "CI/CD全流程执行结束，状态：${{ job.status }}"
