name: CI/CD自动部署Flask
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 拉取仓库代码
        uses: actions/checkout@v4

      - name: 加载SSH私钥，连接云服务器
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: SSH登录服务器，更新代码
        run: ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }} "rm -f /etc/docker/daemon.json;systemctl daemon-reload;systemctl stop docker;sleep 3;systemctl start docker;mkdir -p /home/gxy20/simple-web-cicd;cd /home/gxy20/simple-web-cicd;if [ ! -d .git ];then git clone https://github.com/yi0509/simple-web-cicd.git .; fi;git pull origin main;echo '代码同步完成，服务器DNS故障，跳过Docker构建'"
